## Synthetic population pipeline for Île-de-France
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /mnt/workplace/research/projects/synthetic_population/tmp/cache_3

# This section defines which parts of the pipeline should be run
run:
#  - synthesis.output # To create the output population in the output_path (see below)
  - matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 4

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: edgt_lyon
  edgt_lyon_source: adisp
  # Define sampling rate and random seed for the output population
  sampling_rate: 0.001
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: /mnt/workplace/research/projects/synthetic_population/data
  output_path: /mnt/workplace/research/projects/synthetic_population/tmp/output_3
  regions: [ ]
  departments: [69]
  metropolis: lyon
  # Only interesting if you run the simulation
  java_memory: 14G
